### ISSUE TITLE
[Bug] Error macro 'dbt_macro__create_schema' takes not more than 1 argument(s) while doing snapshots

### ISSUE THREAD

**Issue by ricardoalexanderh** [oracle/dbt-oracle#151]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I got this error when running dbt snapshot

03:36:00  Running with dbt=1.8.3
03:36:00  oracle adapter: Running in thin mode
03:36:01  Registered adapter: oracle=1.8.0
03:36:03  Found 1 snapshot, 1 source, 464 macros
03:36:03
03:36:04  Concurrency: 1 threads (target='dev')
03:36:04
03:36:04  1 of 1 START snapshot CUSTOMER_SNAPSHOTS.customers_snapshot_check .............. [RUN]
03:36:04  1 of 1 ERROR snapshotting CUSTOMER_SNAPSHOTS.customers_snapshot_check .......... [ERROR in 0.21s]
03:36:04
03:36:04  Finished running 1 snapshot in 0 hours 0 minutes and 0.95 seconds (0.95s).
03:36:04
03:36:04  Completed with 1 error and 0 warnings:
03:36:04
03:36:04    Compilation Error in snapshot customers_snapshot_check (snapshots\customers_snapshot_check.sql)
  macro 'dbt_macro__create_schema' takes not more than 1 argument(s)

  > in macro materialization_snapshot_oracle (macros\materializations\snapshot\snapshot.sql)
  > called by snapshot customers_snapshot_check (snapshots\customers_snapshot_check.sql)
03:36:04
03:36:04  Done. PASS=0 WARN=0 ERROR=1 SKIP=0 TOTAL=1

### Expected Behavior

Snapshot run successfully

### Steps To Reproduce

1. Create a snapshot

{% snapshot customers_snapshot_check %}

    {{
        config(
          target_schema='CUSTOMER_SNAPSHOTS',
          strategy='check',
          unique_key='CUSTOMER_ID',
          check_cols=['CUSTOMER_NAME'],
          invalidate_hard_deletes=True
        )
    }}

    select * from {{ source('dbksei', 'CUSTOMER') }}

{% endsnapshot %}

3. Run dbt snapshot

### Environment

```markdown
- OS: Windows 10
- Python: 3.9.6
- dbt: 1.8.3
```

### What Oracle database version are you using dbt with?

18c

**Comment by aosingh** [comment]
@ricardoalexanderh 

Quick question, was this working with dbt-oracle 1.7 and now it fails with dbt-oracle 1.8 ?

**Comment by aosingh** [comment]
@ricardoalexanderh 

I have added a fix for this problem in `dbt-oracle==1.8.1b1`. Could you try with it ? 

To install the fixed version, run the following command:

```
pip install dbt-oracle==1.8.1b1
```

**Comment by aosingh** [comment]
@ricardoalexanderh Did you get a chance to verify the fix ?

**Comment by ricardoalexanderh** [comment]
Sorry for the late response, been busy with other things. I finally been able to run it. I think it is because of the invalid target schema. We can consider this closed.

Thanks

**Comment by bh-kwalker** [comment]
Hi, we are receiving a similar error when running our dbt project in v1.8 for dbt-datbricks and core. Except it is saying " macro 'dbt_macro__location_clause' takes not more than 0 argument(s)" 

This runs fine in any version <1.8

Thanks!
